name: CannonFix
version: 2.1.0
main: com.cannonfix.CannonFix
api-version: '1.21'
author: Claude
description: TNT explosion optimization only - does not modify config files

commands:
  cannonfix:
    aliases: [cf]

permissions:
  cannonfix.reload:
    default: op
