name: CannonFix
version: 1.1.0
main: com.cannonfix.CannonFix
api-version: '1.21'
author: Claude
description: Fixes falling block and TNT issues for factions cannoning. Auto-configures server for optimal cannon performance.

commands:
  cannonfix:
    description: CannonFix main command
    usage: /<command> [reload|status|test|fixworld]
    aliases: [cf, cannon]

permissions:
  cannonfix.*:
    description: All CannonFix permissions
    default: op
    children:
      cannonfix.reload: true
      cannonfix.status: true
      cannonfix.test: true
      cannonfix.fixworld: true
  cannonfix.reload:
    description: Reload config
    default: op
  cannonfix.status:
    description: View status
    default: op
  cannonfix.test:
    description: Run tests
    default: op
  cannonfix.fixworld:
    description: Fix world gamerules
    default: op
